import type {
  VendorFull,
  DevicePosture,
  DeviceEntry,
  TeacherStatus,
  RemediationItem,
  IncidentEvent,
  IncidentTrendPoint,
} from "./nist-mock-data"

export const VENDORS_FULL: VendorFull[] = [
  {
    id: 1,
    name: "Google Workspace",
    service: "Email, Drive, Classroom",
    dataSensitivity: "High",
    riskRating: "Low",
    riskStatus: "Approved",
    contractStatus: "Active",
    contractExpiry: "2025-12-31",
    lastReview: "2026-02-15",
    dataAccess: "Student emails, assignments, documents",
    notes: "SOC 2 certified, strong encryption",
  },
  {
    id: 2,
    name: "Microsoft 365",
    service: "OneDrive, Teams, Office",
    dataSensitivity: "High",
    riskRating: "Low",
    riskStatus: "Approved",
    contractStatus: "Active",
    contractExpiry: "2026-06-30",
    lastReview: "2026-01-20",
    dataAccess: "Student documents, communication",
    notes: "Enterprise agreement, full audit trail",
  },
  {
    id: 3,
    name: "Clever",
    service: "Identity Management",
    dataSensitivity: "High",
    riskRating: "Medium",
    riskStatus: "Approved",
    contractStatus: "Active",
    contractExpiry: "2025-08-15",
    lastReview: "2026-02-01",
    dataAccess: "User accounts, roster sync",
    notes: "FERPA compliant, regular updates needed",
  },
  {
    id: 4,
    name: "Schoology",
    service: "Learning Management System",
    dataSensitivity: "High",
    riskRating: "Medium",
    riskStatus: "Under Review",
    contractStatus: "Active",
    contractExpiry: "2025-09-30",
    lastReview: "2025-12-10",
    dataAccess: "Grades, assignments, student data",
    notes: "Security assessment in progress",
  },
  {
    id: 5,
    name: "Zoom",
    service: "Video Conferencing",
    dataSensitivity: "Medium",
    riskRating: "Medium",
    riskStatus: "Approved",
    contractStatus: "Active",
    contractExpiry: "2026-03-31",
    lastReview: "2026-01-15",
    dataAccess: "Real-time communications",
    notes: "End-to-end encryption enabled for K-12",
  },
  {
    id: 6,
    name: "IXL",
    service: "Adaptive Learning",
    dataSensitivity: "High",
    riskRating: "Medium",
    riskStatus: "Approved",
    contractStatus: "Active",
    contractExpiry: "2025-07-31",
    lastReview: "2025-11-20",
    dataAccess: "Student learning progress, performance",
    notes: "Annual security audit scheduled",
  },
  {
    id: 7,
    name: "Turnitin",
    service: "Academic Integrity",
    dataSensitivity: "High",
    riskRating: "Low",
    riskStatus: "Approved",
    contractStatus: "Active",
    contractExpiry: "2026-05-15",
    lastReview: "2026-02-10",
    dataAccess: "Student submissions, plagiarism detection",
    notes: "Industry standard for plagiarism detection",
  },
  {
    id: 8,
    name: "Powerschool",
    service: "Student Information System",
    dataSensitivity: "High",
    riskRating: "Medium",
    riskStatus: "Under Review",
    contractStatus: "Active",
    contractExpiry: "2025-12-31",
    lastReview: "2025-10-05",
    dataAccess: "Student records, grades, attendance",
    notes: "Penetration test required before renewal",
  },
  {
    id: 9,
    name: "Canva",
    service: "Design & Creative",
    dataSensitivity: "Low",
    riskRating: "Low",
    riskStatus: "Approved",
    contractStatus: "Active",
    contractExpiry: "2026-04-30",
    lastReview: "2026-01-25",
    dataAccess: "Student designs, limited data",
    notes: "Low-risk creative tool",
  },
  {
    id: 10,
    name: "Pear Deck",
    service: "Interactive Presentations",
    dataSensitivity: "Medium",
    riskRating: "Low",
    riskStatus: "Approved",
    contractStatus: "Active",
    contractExpiry: "2025-11-30",
    lastReview: "2025-09-15",
    dataAccess: "Real-time student responses",
    notes: "COPPA compliant",
  },
  {
    id: 11,
    name: "Nearpod",
    service: "Student Engagement",
    dataSensitivity: "Medium",
    riskRating: "Medium",
    riskStatus: "Approved",
    contractStatus: "Pending",
    contractExpiry: "2026-08-31",
    lastReview: "2026-02-28",
    dataAccess: "Student engagement data",
    notes: "Contract renewal negotiation ongoing",
  },
  {
    id: 12,
    name: "Lexmark Print Services",
    service: "Printing & Imaging",
    dataSensitivity: "Medium",
    riskRating: "High",
    riskStatus: "At Risk",
    contractStatus: "Active",
    contractExpiry: "2025-06-30",
    lastReview: "2025-08-01",
    dataAccess: "Student documents printed",
    notes: "Firmware update overdue, risk mitigation plan needed",
  },
]

export const DEVICE_POSTURE: DevicePosture = {
  total: 847,
  compliant: 762,
  patchPercentage: 91,
  antivirusPercentage: 94,
  highRiskDevices: [
    {
      deviceId: "DEV-2021-0847",
      deviceName: "Lab-Computer-12",
      os: "Windows 10 (Build 19044)",
      lastPatchDate: "2025-11-15",
      patchStatus: "Overdue",
      riskLevel: "Critical",
    },
    {
      deviceId: "DEV-2019-0234",
      deviceName: "Student-Laptop-09",
      os: "macOS 11.0",
      lastPatchDate: "2025-10-20",
      patchStatus: "Overdue",
      riskLevel: "High",
    },
    {
      deviceId: "DEV-2020-0512",
      deviceName: "Teacher-Desktop-05",
      os: "Windows 11",
      lastPatchDate: "2026-01-10",
      patchStatus: "Overdue",
      riskLevel: "High",
    },
    {
      deviceId: "DEV-2022-0156",
      deviceName: "Library-iPad-03",
      os: "iPadOS 16.3",
      lastPatchDate: "2025-12-05",
      patchStatus: "Critical",
      riskLevel: "High",
    },
    {
      deviceId: "DEV-2018-0098",
      deviceName: "Server-VM-02",
      os: "Ubuntu 18.04 LTS",
      lastPatchDate: "2025-09-30",
      patchStatus: "Overdue",
      riskLevel: "Critical",
    },
  ],
}

export const TEACHER_STATUS: TeacherStatus[] = [
  { name: "Sarah Johnson", mfaEnabled: true, passwordStatus: "Current", lastLogin: "2026-03-11", deviceCompliance: 100, trainingProgress: 95 },
  { name: "Michael Chen", mfaEnabled: true, passwordStatus: "Current", lastLogin: "2026-03-10", deviceCompliance: 95, trainingProgress: 88 },
  { name: "Maria Garcia", mfaEnabled: false, passwordStatus: "Expired Soon", lastLogin: "2026-03-09", deviceCompliance: 78, trainingProgress: 72 },
  { name: "David Kim", mfaEnabled: true, passwordStatus: "Current", lastLogin: "2026-03-11", deviceCompliance: 100, trainingProgress: 100 },
  { name: "Lisa Wong", mfaEnabled: true, passwordStatus: "Current", lastLogin: "2026-03-08", deviceCompliance: 92, trainingProgress: 85 },
]

export const APPROVED_TOOLS = [
  { name: "Google Classroom", status: "Approved", category: "Learning Management" },
  { name: "Khan Academy", status: "Approved", category: "Educational Content" },
  { name: "Desmos", status: "Approved", category: "Math Tools" },
  { name: "Scratch", status: "Approved", category: "Programming" },
  { name: "Canva", status: "Approved", category: "Design" },
  { name: "YouTube (Educational)", status: "Conditional", category: "Video Content" },
  { name: "ChatGPT", status: "Conditional", category: "AI Tools" },
  { name: "Wikipedia", status: "Approved", category: "Reference" },
  { name: "TikTok", status: "Restricted", category: "Social Media" },
  { name: "Instagram", status: "Restricted", category: "Social Media" },
]

export const REMEDIATION_ITEMS: RemediationItem[] = [
  {
    id: 1,
    title: "Patch 12 Critical Devices",
    domain: "Device Management",
    dueDate: "2026-03-15",
    owner: "IT Admin",
    status: "Overdue",
    priority: "Critical",
  },
  {
    id: 2,
    title: "Update Lexmark Firmware",
    domain: "Printing Services",
    dueDate: "2026-03-12",
    owner: "Infrastructure",
    status: "Due Soon",
    priority: "High",
  },
  {
    id: 3,
    title: "Complete MFA Rollout (98% done)",
    domain: "Authentication",
    dueDate: "2026-03-20",
    owner: "Security Team",
    status: "On Track",
    priority: "High",
  },
  {
    id: 4,
    title: "Vendor Security Assessment - Schoology",
    domain: "Vendor Management",
    dueDate: "2026-04-01",
    owner: "Compliance",
    status: "On Track",
    priority: "Medium",
  },
  {
    id: 5,
    title: "Network Segmentation Phase 2",
    domain: "Network Security",
    dueDate: "2026-05-15",
    owner: "Infrastructure",
    status: "On Track",
    priority: "Medium",
  },
  {
    id: 6,
    title: "Incident Response Tabletop Exercise",
    domain: "Incident Response",
    dueDate: "2026-03-25",
    owner: "Security Team",
    status: "On Track",
    priority: "Medium",
  },
  {
    id: 7,
    title: "Contract Renewal - Powerschool",
    domain: "Vendor Management",
    dueDate: "2026-04-15",
    owner: "Procurement",
    status: "On Track",
    priority: "High",
  },
  {
    id: 8,
    title: "Staff Security Training Refresher",
    domain: "Awareness & Training",
    dueDate: "2026-06-30",
    owner: "HR/Security",
    status: "On Track",
    priority: "Medium",
  },
]

export const INCIDENT_EVENTS: IncidentEvent[] = [
  {
    id: 1,
    date: "2026-03-10",
    title: "Phishing campaign detected",
    type: "Email Security",
    severity: "High",
    status: "Resolved",
    mttr: "45 min",
  },
  {
    id: 2,
    date: "2026-03-09",
    title: "Student data export unauthorized",
    type: "Data Access",
    severity: "Critical",
    status: "Resolved",
    mttr: "2.5 hrs",
  },
  {
    id: 3,
    date: "2026-03-08",
    title: "Suspicious VPN activity detected",
    type: "Network",
    severity: "Medium",
    status: "Resolved",
    mttr: "30 min",
  },
  {
    id: 4,
    date: "2026-03-07",
    title: "Certificate expiration warning",
    type: "Infrastructure",
    severity: "Medium",
    status: "Resolved",
    mttr: "15 min",
  },
  {
    id: 5,
    date: "2026-03-06",
    title: "Password spray attempt detected",
    type: "Authentication",
    severity: "High",
    status: "Resolved",
    mttr: "1 hr",
  },
  {
    id: 6,
    date: "2026-03-05",
    title: "Malware detected in attachment",
    type: "Malware",
    severity: "High",
    status: "Resolved",
    mttr: "2 hrs",
  },
  {
    id: 7,
    date: "2026-03-04",
    title: "Unauthorized access attempt",
    type: "Access Control",
    severity: "Medium",
    status: "Resolved",
    mttr: "25 min",
  },
  {
    id: 8,
    date: "2026-03-03",
    title: "Data exfiltration attempt blocked",
    type: "DLP",
    severity: "Critical",
    status: "Resolved",
    mttr: "3 hrs",
  },
  {
    id: 9,
    date: "2026-03-02",
    title: "Zero-day vulnerability patched",
    type: "Vulnerability",
    severity: "Critical",
    status: "Resolved",
    mttr: "1.5 hrs",
  },
  {
    id: 10,
    date: "2026-03-01",
    title: "Database backup failure",
    type: "Backup/Recovery",
    severity: "High",
    status: "Resolved",
    mttr: "4 hrs",
  },
  {
    id: 11,
    date: "2026-02-28",
    title: "API rate limiting triggered",
    type: "Application",
    severity: "Low",
    status: "Resolved",
    mttr: "10 min",
  },
  {
    id: 12,
    date: "2026-02-27",
    title: "SSL certificate warning",
    type: "Infrastructure",
    severity: "Medium",
    status: "Resolved",
    mttr: "20 min",
  },
  {
    id: 13,
    date: "2026-02-26",
    title: "Vendor portal compromised",
    type: "Vendor Risk",
    severity: "High",
    status: "Investigating",
    mttr: "Ongoing",
  },
  {
    id: 14,
    date: "2026-02-25",
    title: "Ransomware detection",
    type: "Malware",
    severity: "Critical",
    status: "Resolved",
    mttr: "6 hrs",
  },
  {
    id: 15,
    date: "2026-02-24",
    title: "Student data disclosure",
    type: "Data Loss",
    severity: "Critical",
    status: "Resolved",
    mttr: "5 hrs",
  },
  {
    id: 16,
    date: "2026-02-23",
    title: "Insider threat alert",
    type: "Insider Threat",
    severity: "High",
    status: "Investigating",
    mttr: "Ongoing",
  },
  {
    id: 17,
    date: "2026-02-22",
    title: "DDoS attack mitigated",
    type: "Network",
    severity: "High",
    status: "Resolved",
    mttr: "1 hr",
  },
  {
    id: 18,
    date: "2026-02-21",
    title: "Account takeover detected",
    type: "Authentication",
    severity: "High",
    status: "Resolved",
    mttr: "45 min",
  },
  {
    id: 19,
    date: "2026-02-20",
    title: "Configuration drift detected",
    type: "Configuration",
    severity: "Medium",
    status: "Resolved",
    mttr: "2 hrs",
  },
  {
    id: 20,
    date: "2026-02-19",
    title: "Security log tampering detected",
    type: "Audit",
    severity: "Critical",
    status: "Resolved",
    mttr: "7 hrs",
  },
]

export const INCIDENT_TREND_BY_WEEK: IncidentTrendPoint[] = [
  { week: "Feb 17-23", Critical: 3, High: 5, Medium: 4, Low: 2 },
  { week: "Feb 24-Mar 2", Critical: 2, High: 6, Medium: 3, Low: 3 },
  { week: "Mar 3-9", Critical: 2, High: 4, Medium: 5, Low: 1 },
  { week: "Mar 10-16", Critical: 1, High: 3, Medium: 2, Low: 2 },
]

export const PARENT_FAQ = [
  {
    question: "How is my child's data protected?",
    answer: "We use multiple layers of security including encryption, access controls, and regular audits. All student data is encrypted both in transit and at rest.",
  },
  {
    question: "What third-party services does the school use?",
    answer: "We carefully vet all third-party vendors. A complete list is available on our security website. All services meet FERPA and K-12 security standards.",
  },
  {
    question: "What should I do if I suspect a security issue?",
    answer: "Please contact our security team immediately at security@district.k12.edu. Report any suspicious emails, unauthorized access, or data concerns.",
  },
  {
    question: "How are incidents handled?",
    answer: "We have a comprehensive incident response plan. Critical incidents are reported to families within 24 hours. Our average response time is under 1 hour.",
  },
  {
    question: "Can I request my child's data?",
    answer: "Yes. Submit a FERPA request to privacy@district.k12.edu. We provide all collected data within 30 days.",
  },
  {
    question: "What training do staff receive?",
    answer: "All staff complete annual security and privacy training. Teachers receive quarterly refreshers on handling student data securely.",
  },
]

export const PARENT_PROTECTION_CARDS = [
  {
    title: "Student Data Protection",
    score: 94,
    icon: "🔐",
    whatItMeans: "Your child's personal information is encrypted and protected with strong security measures.",
    whyItMatters: "Student data is sensitive and valuable. Strong protection prevents identity theft and unauthorized access.",
    whatSchoolDoes: "We use enterprise-grade encryption, regular security audits, and strict access controls.",
  },
  {
    title: "Secure Login",
    score: 89,
    icon: "🔑",
    whatItMeans: "Multi-factor authentication ensures only authorized users can access student accounts.",
    whyItMatters: "Strong authentication prevents unauthorized account access and protects against credential theft.",
    whatSchoolDoes: "We require strong passwords and are rolling out multi-factor authentication district-wide.",
  },
  {
    title: "Safe Platforms",
    score: 87,
    icon: "🛡️",
    whatItMeans: "All educational platforms are vetted for security and compliance with K-12 standards.",
    whyItMatters: "Students spend significant time in these platforms. They must be secure and privacy-respecting.",
    whatSchoolDoes: "We perform security assessments on all platforms and maintain an approved tools list.",
  },
  {
    title: "Vendor Reviews",
    score: 85,
    icon: "✅",
    whatItMeans: "All third-party vendors undergo security and privacy reviews before being approved.",
    whyItMatters: "Vendors have access to student data. Thorough vetting reduces risk of breaches.",
    whatSchoolDoes: "We review contracts, require SOC 2 certification, and perform periodic audits.",
  },
  {
    title: "Threat Monitoring",
    score: 92,
    icon: "👁️",
    whatItMeans: "Continuous monitoring detects and responds to security threats 24/7.",
    whyItMatters: "Early detection of threats prevents data loss and unauthorized access.",
    whatSchoolDoes: "We use advanced monitoring tools and maintain an incident response team.",
  },
  {
    title: "Incident Readiness",
    score: 88,
    icon: "🚨",
    whatItMeans: "We have a plan to quickly respond to and communicate about security incidents.",
    whyItMatters: "Rapid response minimizes damage and keeps families informed.",
    whatSchoolDoes: "We conduct regular drills and maintain 24-hour incident response capabilities.",
  },
]

export const STAFF_RESPONSIBILITIES = [
  {
    title: "Recognize Phishing",
    description: "Be alert to suspicious emails requesting personal or financial information.",
    icon: "📧",
    action: "Report suspicious emails to security@district.k12.edu",
  },
  {
    title: "Keep Passwords Secure",
    description: "Use strong, unique passwords and never share them with anyone.",
    icon: "🔑",
    action: "Use password manager and enable multi-factor authentication",
  },
  {
    title: "Lock Your Device",
    description: "Always lock your computer or mobile device when leaving it unattended.",
    icon: "🔒",
    action: "Enable auto-lock with 5-minute timeout",
  },
  {
    title: "Handle Data Carefully",
    description: "Only access student data you need, and protect printed materials.",
    icon: "📋",
    action: "Follow data handling policy and shred sensitive documents",
  },
  {
    title: "Report Incidents",
    description: "Immediately report any security concerns or suspicious activity.",
    icon: "🚨",
    action: "Contact security team within 1 hour of discovery",
  },
]

// Admin console mock data (16 new exports)

export const SECURITY_SCORE_TREND = [
  {
    month: "October",
    Authentication: 78,
    DeviceSecurity: 81,
    DataProtection: 85,
    VendorRisk: 72,
    IncidentResponse: 79,
  },
  {
    month: "November",
    Authentication: 81,
    DeviceSecurity: 84,
    DataProtection: 87,
    VendorRisk: 75,
    IncidentResponse: 82,
  },
  {
    month: "December",
    Authentication: 84,
    DeviceSecurity: 87,
    DataProtection: 89,
    VendorRisk: 78,
    IncidentResponse: 85,
  },
  {
    month: "January",
    Authentication: 86,
    DeviceSecurity: 89,
    DataProtection: 91,
    VendorRisk: 81,
    IncidentResponse: 87,
  },
  {
    month: "February",
    Authentication: 88,
    DeviceSecurity: 91,
    DataProtection: 93,
    VendorRisk: 83,
    IncidentResponse: 89,
  },
  {
    month: "March",
    Authentication: 90,
    DeviceSecurity: 92,
    DataProtection: 94,
    VendorRisk: 85,
    IncidentResponse: 91,
  },
]

export const DOMAIN_RISK_RADAR = [
  { domain: "Authentication", score: 90, status: "Excellent" },
  { domain: "Device Security", score: 92, status: "Excellent" },
  { domain: "Data Protection", score: 94, status: "Excellent" },
  { domain: "Vendor Management", score: 85, status: "Good" },
  { domain: "Incident Response", score: 91, status: "Excellent" },
  { domain: "Network Security", score: 88, status: "Good" },
  { domain: "Access Control", score: 87, status: "Good" },
  { domain: "Compliance", score: 89, status: "Good" },
]

export const ADMIN_USERS = [
  {
    id: 1,
    name: "Sarah Johnson",
    email: "sjohnson@district.k12.edu",
    role: "admin",
    mfaEnabled: true,
    mfaMethod: "TOTP",
    lastLogin: "2026-03-11T14:30:00Z",
    status: "Active",
    department: "Security",
    createdAt: "2024-01-15",
  },
  {
    id: 2,
    name: "Michael Chen",
    email: "mchen@district.k12.edu",
    role: "admin",
    mfaEnabled: true,
    mfaMethod: "TOTP",
    lastLogin: "2026-03-11T09:15:00Z",
    status: "Active",
    department: "IT",
    createdAt: "2023-08-20",
  },
  {
    id: 3,
    name: "Lisa Wong",
    email: "lwong@district.k12.edu",
    role: "admin",
    mfaEnabled: true,
    mfaMethod: "SMS",
    lastLogin: "2026-03-10T16:45:00Z",
    status: "Active",
    department: "Compliance",
    createdAt: "2023-11-10",
  },
  {
    id: 4,
    name: "James Wilson",
    email: "jwilson@district.k12.edu",
    role: "admin",
    mfaEnabled: true,
    mfaMethod: "TOTP",
    lastLogin: "2026-03-09T11:20:00Z",
    status: "Active",
    department: "Infrastructure",
    createdAt: "2023-05-01",
  },
  {
    id: 5,
    name: "Emma Davis",
    email: "edavis@district.k12.edu",
    role: "teacher",
    mfaEnabled: true,
    mfaMethod: "TOTP",
    lastLogin: "2026-03-11T13:10:00Z",
    status: "Active",
    department: "High School",
    createdAt: "2022-09-01",
  },
  {
    id: 6,
    name: "David Kim",
    email: "dkim@district.k12.edu",
    role: "teacher",
    mfaEnabled: true,
    mfaMethod: "SMS",
    lastLogin: "2026-03-11T08:30:00Z",
    status: "Active",
    department: "Middle School",
    createdAt: "2022-08-15",
  },
  {
    id: 7,
    name: "Maria Garcia",
    email: "mgarcia@district.k12.edu",
    role: "teacher",
    mfaEnabled: false,
    mfaMethod: "None",
    lastLogin: "2026-03-10T14:45:00Z",
    status: "Active",
    department: "Elementary",
    createdAt: "2023-01-10",
  },
  {
    id: 8,
    name: "John Smith",
    email: "jsmith@district.k12.edu",
    role: "teacher",
    mfaEnabled: true,
    mfaMethod: "TOTP",
    lastLogin: "2026-03-11T12:00:00Z",
    status: "Active",
    department: "High School",
    createdAt: "2022-07-20",
  },
  {
    id: 9,
    name: "Sarah Martinez",
    email: "smartinez@district.k12.edu",
    role: "teacher",
    mfaEnabled: false,
    mfaMethod: "None",
    lastLogin: "2026-03-09T10:15:00Z",
    status: "Active",
    department: "Elementary",
    createdAt: "2023-02-01",
  },
  {
    id: 10,
    name: "Robert Taylor",
    email: "rtaylor@district.k12.edu",
    role: "teacher",
    mfaEnabled: true,
    mfaMethod: "SMS",
    lastLogin: "2026-03-11T15:30:00Z",
    status: "Active",
    department: "Middle School",
    createdAt: "2022-09-05",
  },
  {
    id: 11,
    name: "Jennifer Lee",
    email: "jlee@district.k12.edu",
    role: "teacher",
    mfaEnabled: true,
    mfaMethod: "TOTP",
    lastLogin: "2026-03-10T09:45:00Z",
    status: "Active",
    department: "High School",
    createdAt: "2023-01-15",
  },
  {
    id: 12,
    name: "Thomas Brown",
    email: "tbrown@district.k12.edu",
    role: "teacher",
    mfaEnabled: false,
    mfaMethod: "None",
    lastLogin: "2026-03-08T13:20:00Z",
    status: "Suspended",
    department: "Elementary",
    createdAt: "2022-10-01",
  },
  {
    id: 13,
    name: "Patricia Anderson",
    email: "panderson@district.k12.edu",
    role: "teacher",
    mfaEnabled: true,
    mfaMethod: "SMS",
    lastLogin: "2026-03-11T10:30:00Z",
    status: "Active",
    department: "Middle School",
    createdAt: "2023-03-01",
  },
  {
    id: 14,
    name: "Christopher Johnson",
    email: "cjohnson@district.k12.edu",
    role: "staff",
    mfaEnabled: true,
    mfaMethod: "TOTP",
    lastLogin: "2026-03-11T14:15:00Z",
    status: "Active",
    department: "IT Support",
    createdAt: "2023-06-01",
  },
  {
    id: 15,
    name: "Susan White",
    email: "swhite@district.k12.edu",
    role: "staff",
    mfaEnabled: false,
    mfaMethod: "None",
    lastLogin: "2026-03-10T11:00:00Z",
    status: "Pending",
    department: "HR",
    createdAt: "2026-02-01",
  },
  {
    id: 16,
    name: "Daniel Harris",
    email: "dharris@district.k12.edu",
    role: "staff",
    mfaEnabled: true,
    mfaMethod: "SMS",
    lastLogin: "2026-03-11T09:30:00Z",
    status: "Active",
    department: "Finance",
    createdAt: "2024-04-15",
  },
  {
    id: 17,
    name: "Nancy Thomas",
    email: "nthomas@district.k12.edu",
    role: "staff",
    mfaEnabled: false,
    mfaMethod: "None",
    lastLogin: "2026-03-09T15:45:00Z",
    status: "Active",
    department: "Facilities",
    createdAt: "2023-09-10",
  },
  {
    id: 18,
    name: "Paul Jackson",
    email: "pjackson@district.k12.edu",
    role: "parent",
    mfaEnabled: false,
    mfaMethod: "None",
    lastLogin: "2026-03-07T20:30:00Z",
    status: "Active",
    department: "Community",
    createdAt: "2024-09-01",
  },
  {
    id: 19,
    name: "Karen Martin",
    email: "kmartin@district.k12.edu",
    role: "parent",
    mfaEnabled: false,
    mfaMethod: "None",
    lastLogin: "2026-02-28T19:15:00Z",
    status: "Active",
    department: "Community",
    createdAt: "2024-08-15",
  },
  {
    id: 20,
    name: "Steven Robinson",
    email: "srobinson@district.k12.edu",
    role: "teacher",
    mfaEnabled: true,
    mfaMethod: "TOTP",
    lastLogin: "2026-03-11T16:00:00Z",
    status: "Active",
    department: "High School",
    createdAt: "2022-06-01",
  },
]

export const USER_ROLE_DISTRIBUTION = [
  { role: "Admin", count: 8, color: "#ef4444" },
  { role: "Teacher", count: 127, color: "#3b82f6" },
  { role: "Staff", count: 34, color: "#10b981" },
  { role: "Parent", count: 412, color: "#f59e0b" },
]

export const USER_ACTIVITY_BY_MONTH = [
  { month: "October", logins: 2340, failures: 45, newUsers: 12 },
  { month: "November", logins: 2580, failures: 38, newUsers: 18 },
  { month: "December", logins: 2120, failures: 52, newUsers: 8 },
  { month: "January", logins: 2890, failures: 31, newUsers: 22 },
  { month: "February", logins: 3120, failures: 28, newUsers: 15 },
  { month: "March", logins: 3450, failures: 24, newUsers: 25 },
]

export const MFA_ENFORCEMENT = [
  { department: "Security", total: 8, enrolled: 8, exempt: 0, pending: 0 },
  { department: "IT", total: 34, enrolled: 32, exempt: 1, pending: 1 },
  { department: "Administration", total: 45, enrolled: 42, exempt: 2, pending: 1 },
  { department: "Teachers", total: 127, enrolled: 98, exempt: 8, pending: 21 },
  { department: "Support Staff", total: 34, enrolled: 8, exempt: 12, pending: 14 },
]

export const MFA_METHOD_BREAKDOWN = [
  { method: "TOTP", count: 141, percentage: 75 },
  { method: "SMS", count: 28, percentage: 15 },
  { method: "Email", count: 17, percentage: 9 },
  { method: "None", count: 2, percentage: 1 },
]

export const ALL_DEVICES = [
  {
    id: "LAP-001",
    name: "Admin-Laptop-01",
    type: "Laptop",
    os: "Windows 11 Pro",
    assignedTo: "Sarah Johnson",
    department: "Security",
    lastSeen: "2026-03-11T16:30:00Z",
    patchStatus: "Up to Date",
    encryptionStatus: "Enabled",
    antivirusStatus: "Active",
    riskScore: 8,
    riskLevel: "Low",
  },
  {
    id: "LAP-002",
    name: "Teacher-Laptop-05",
    type: "Laptop",
    os: "macOS 14.2",
    assignedTo: "Emma Davis",
    department: "High School",
    lastSeen: "2026-03-11T15:45:00Z",
    patchStatus: "Up to Date",
    encryptionStatus: "Enabled",
    antivirusStatus: "Active",
    riskScore: 12,
    riskLevel: "Low",
  },
  {
    id: "DES-042",
    name: "Lab-Desktop-12",
    type: "Desktop",
    os: "Windows 10 Build 19044",
    assignedTo: "IT Lab",
    department: "IT",
    lastSeen: "2026-03-11T08:15:00Z",
    patchStatus: "Overdue",
    encryptionStatus: "Partial",
    antivirusStatus: "Outdated",
    riskScore: 72,
    riskLevel: "Critical",
  },
  {
    id: "IPD-015",
    name: "Library-iPad-03",
    type: "iPad",
    os: "iPadOS 17.1",
    assignedTo: "Library",
    department: "Elementary",
    lastSeen: "2026-03-10T17:30:00Z",
    patchStatus: "Critical",
    encryptionStatus: "Enabled",
    antivirusStatus: "Active",
    riskScore: 58,
    riskLevel: "High",
  },
  {
    id: "CHR-089",
    name: "Student-Chromebook-24",
    type: "Chromebook",
    os: "ChromeOS 122",
    assignedTo: "Classroom 215",
    department: "Middle School",
    lastSeen: "2026-03-11T14:00:00Z",
    patchStatus: "Up to Date",
    encryptionStatus: "Enabled",
    antivirusStatus: "Active",
    riskScore: 5,
    riskLevel: "Low",
  },
  {
    id: "SRV-001",
    name: "Auth-Server-01",
    type: "Server",
    os: "Ubuntu 22.04 LTS",
    assignedTo: "Infrastructure",
    department: "IT",
    lastSeen: "2026-03-11T16:45:00Z",
    patchStatus: "Up to Date",
    encryptionStatus: "Enabled",
    antivirusStatus: "Active",
    riskScore: 15,
    riskLevel: "Low",
  },
  {
    id: "LAP-008",
    name: "Teacher-Laptop-11",
    type: "Laptop",
    os: "Windows 11",
    assignedTo: "David Kim",
    department: "Middle School",
    lastSeen: "2026-03-11T13:20:00Z",
    patchStatus: "Up to Date",
    encryptionStatus: "Enabled",
    antivirusStatus: "Active",
    riskScore: 10,
    riskLevel: "Low",
  },
  {
    id: "DES-089",
    name: "Office-Desktop-08",
    type: "Desktop",
    os: "Windows 11 Pro",
    assignedTo: "Admin Office",
    department: "Administration",
    lastSeen: "2026-03-09T09:30:00Z",
    patchStatus: "Overdue",
    encryptionStatus: "Enabled",
    antivirusStatus: "Outdated",
    riskScore: 45,
    riskLevel: "High",
  },
  {
    id: "IPD-032",
    name: "Classroom-iPad-07",
    type: "iPad",
    os: "iPadOS 16.7",
    assignedTo: "Classroom 105",
    department: "Elementary",
    lastSeen: "2026-03-08T16:00:00Z",
    patchStatus: "Critical",
    encryptionStatus: "Disabled",
    antivirusStatus: "Missing",
    riskScore: 82,
    riskLevel: "Critical",
  },
  {
    id: "CHR-156",
    name: "Student-Chromebook-67",
    type: "Chromebook",
    os: "ChromeOS 122",
    assignedTo: "Cart 5",
    department: "High School",
    lastSeen: "2026-03-11T12:15:00Z",
    patchStatus: "Up to Date",
    encryptionStatus: "Enabled",
    antivirusStatus: "Active",
    riskScore: 6,
    riskLevel: "Low",
  },
  {
    id: "LAP-014",
    name: "Teacher-Laptop-19",
    type: "Laptop",
    os: "macOS 13.5",
    assignedTo: "Maria Garcia",
    department: "Elementary",
    lastSeen: "2026-03-10T15:45:00Z",
    patchStatus: "Up to Date",
    encryptionStatus: "Enabled",
    antivirusStatus: "Active",
    riskScore: 11,
    riskLevel: "Low",
  },
  {
    id: "SRV-003",
    name: "DB-Server-02",
    type: "Server",
    os: "Ubuntu 20.04 LTS",
    assignedTo: "Infrastructure",
    department: "IT",
    lastSeen: "2026-03-11T16:50:00Z",
    patchStatus: "Critical",
    encryptionStatus: "Enabled",
    antivirusStatus: "Active",
    riskScore: 68,
    riskLevel: "High",
  },
  {
    id: "DES-123",
    name: "Graphics-Desktop-09",
    type: "Desktop",
    os: "Windows 10",
    assignedTo: "Art Room",
    department: "High School",
    lastSeen: "2026-03-07T14:20:00Z",
    patchStatus: "Overdue",
    encryptionStatus: "Partial",
    antivirusStatus: "Outdated",
    riskScore: 55,
    riskLevel: "High",
  },
  {
    id: "CHR-201",
    name: "Student-Chromebook-88",
    type: "Chromebook",
    os: "ChromeOS 121",
    assignedTo: "Cart 9",
    department: "Elementary",
    lastSeen: "2026-03-11T11:30:00Z",
    patchStatus: "Up to Date",
    encryptionStatus: "Enabled",
    antivirusStatus: "Active",
    riskScore: 7,
    riskLevel: "Low",
  },
  {
    id: "LAP-027",
    name: "Teacher-Laptop-33",
    type: "Laptop",
    os: "Windows 11",
    assignedTo: "John Smith",
    department: "High School",
    lastSeen: "2026-03-11T10:00:00Z",
    patchStatus: "Up to Date",
    encryptionStatus: "Enabled",
    antivirusStatus: "Active",
    riskScore: 9,
    riskLevel: "Low",
  },
]

export const DEVICE_TYPE_BREAKDOWN = [
  { type: "Chromebook", count: 412 },
  { type: "Laptop", count: 185 },
  { type: "iPad", count: 98 },
  { type: "Desktop", count: 124 },
  { type: "Server", count: 28 },
]

export const DEVICE_PATCH_TREND = [
  { month: "October", compliant: 712, overdue: 98, critical: 37 },
  { month: "November", compliant: 738, overdue: 75, critical: 34 },
  { month: "December", compliant: 745, overdue: 68, critical: 34 },
  { month: "January", compliant: 756, overdue: 58, critical: 33 },
  { month: "February", compliant: 759, overdue: 52, critical: 36 },
  { month: "March", compliant: 762, overdue: 58, critical: 27 },
]

export const VENDOR_ASSESSMENTS = [
  {
    vendorId: 1,
    vendorName: "Google Workspace",
    assessmentDate: "2026-02-15",
    assessor: "Sarah Johnson",
    ferpaCompliant: true,
    coppaCompliant: true,
    soc2Certified: true,
    penetrationTested: true,
    dataEncryption: "AES-256",
    dataResidency: "Multi-region",
    breachHistory: false,
    overallScore: 94,
    recommendation: "Approve",
    nextReview: "2027-02-15",
    findings: "Excellent security posture. No issues identified.",
  },
  {
    vendorId: 2,
    vendorName: "Microsoft 365",
    assessmentDate: "2026-01-20",
    assessor: "Michael Chen",
    ferpaCompliant: true,
    coppaCompliant: true,
    soc2Certified: true,
    penetrationTested: true,
    dataEncryption: "AES-256",
    dataResidency: "US-based",
    breachHistory: false,
    overallScore: 92,
    recommendation: "Approve",
    nextReview: "2027-01-20",
    findings: "Strong security controls. Annual audit recommended.",
  },
  {
    vendorId: 3,
    vendorName: "Clever",
    assessmentDate: "2026-02-01",
    assessor: "Lisa Wong",
    ferpaCompliant: true,
    coppaCompliant: true,
    soc2Certified: true,
    penetrationTested: false,
    dataEncryption: "AES-256",
    dataResidency: "US",
    breachHistory: false,
    overallScore: 85,
    recommendation: "Conditional",
    nextReview: "2026-08-01",
    findings: "Requires penetration testing before renewal.",
  },
  {
    vendorId: 4,
    vendorName: "Schoology",
    assessmentDate: "2025-12-10",
    assessor: "David Kim",
    ferpaCompliant: true,
    coppaCompliant: false,
    soc2Certified: false,
    penetrationTested: false,
    dataEncryption: "TLS",
    dataResidency: "US",
    breachHistory: false,
    overallScore: 68,
    recommendation: "Reassess",
    nextReview: "2026-03-15",
    findings: "Missing SOC 2 certification. COPPA review needed.",
  },
  {
    vendorId: 5,
    vendorName: "Zoom",
    assessmentDate: "2026-01-15",
    assessor: "Emma Davis",
    ferpaCompliant: true,
    coppaCompliant: true,
    soc2Certified: true,
    penetrationTested: true,
    dataEncryption: "AES-256",
    dataResidency: "Global",
    breachHistory: false,
    overallScore: 88,
    recommendation: "Approve",
    nextReview: "2027-01-15",
    findings: "Good security controls. Monitor encryption updates.",
  },
  {
    vendorId: 6,
    vendorName: "IXL",
    assessmentDate: "2025-11-20",
    assessor: "James Wilson",
    ferpaCompliant: true,
    coppaCompliant: true,
    soc2Certified: true,
    penetrationTested: false,
    dataEncryption: "AES-256",
    dataResidency: "US",
    breachHistory: false,
    overallScore: 82,
    recommendation: "Conditional",
    nextReview: "2026-05-20",
    findings: "Annual security audit scheduled for May.",
  },
  {
    vendorId: 7,
    vendorName: "Turnitin",
    assessmentDate: "2026-02-10",
    assessor: "Sarah Johnson",
    ferpaCompliant: true,
    coppaCompliant: true,
    soc2Certified: true,
    penetrationTested: true,
    dataEncryption: "AES-256",
    dataResidency: "US",
    breachHistory: false,
    overallScore: 90,
    recommendation: "Approve",
    nextReview: "2027-02-10",
    findings: "Industry standard security. No concerns.",
  },
  {
    vendorId: 8,
    vendorName: "Powerschool",
    assessmentDate: "2025-10-05",
    assessor: "Michael Chen",
    ferpaCompliant: true,
    coppaCompliant: false,
    soc2Certified: true,
    penetrationTested: false,
    dataEncryption: "AES-256",
    dataResidency: "US",
    breachHistory: false,
    overallScore: 76,
    recommendation: "Reassess",
    nextReview: "2026-04-05",
    findings: "Penetration test required before renewal.",
  },
  {
    vendorId: 9,
    vendorName: "Canva",
    assessmentDate: "2026-01-25",
    assessor: "Lisa Wong",
    ferpaCompliant: true,
    coppaCompliant: true,
    soc2Certified: false,
    penetrationTested: false,
    dataEncryption: "TLS",
    dataResidency: "Global",
    breachHistory: false,
    overallScore: 72,
    recommendation: "Conditional",
    nextReview: "2026-07-25",
    findings: "SOC 2 certification recommended.",
  },
  {
    vendorId: 10,
    vendorName: "Pear Deck",
    assessmentDate: "2025-09-15",
    assessor: "David Kim",
    ferpaCompliant: true,
    coppaCompliant: true,
    soc2Certified: true,
    penetrationTested: true,
    dataEncryption: "AES-256",
    dataResidency: "US",
    breachHistory: false,
    overallScore: 86,
    recommendation: "Approve",
    nextReview: "2026-09-15",
    findings: "COPPA compliant. Good security controls.",
  },
  {
    vendorId: 11,
    vendorName: "Nearpod",
    assessmentDate: "2026-02-28",
    assessor: "Emma Davis",
    ferpaCompliant: true,
    coppaCompliant: true,
    soc2Certified: false,
    penetrationTested: false,
    dataEncryption: "TLS",
    dataResidency: "US",
    breachHistory: false,
    overallScore: 74,
    recommendation: "Conditional",
    nextReview: "2026-08-28",
    findings: "SOC 2 certification in progress.",
  },
  {
    vendorId: 12,
    vendorName: "Lexmark Print Services",
    assessmentDate: "2025-08-01",
    assessor: "James Wilson",
    ferpaCompliant: false,
    coppaCompliant: false,
    soc2Certified: false,
    penetrationTested: false,
    dataEncryption: "None",
    dataResidency: "Unknown",
    breachHistory: true,
    overallScore: 48,
    recommendation: "Reject",
    nextReview: "2026-08-01",
    findings: "High risk. Firmware overdue. Prior breach history.",
  },
]

export const VENDOR_COMPLIANCE_SCORES = [
  { name: "Google Workspace", score: 94 },
  { name: "Microsoft 365", score: 92 },
  { name: "Turnitin", score: 90 },
  { name: "Zoom", score: 88 },
  { name: "Pear Deck", score: 86 },
  { name: "Clever", score: 85 },
  { name: "IXL", score: 82 },
  { name: "Powerschool", score: 76 },
  { name: "Nearpod", score: 74 },
  { name: "Canva", score: 72 },
  { name: "Schoology", score: 68 },
  { name: "Lexmark Print Services", score: 48 },
]

export const ACTIVE_INCIDENTS = [
  {
    id: 1,
    title: "Phishing Campaign - Staff Mailboxes",
    type: "Email Security",
    severity: "High",
    status: "Open",
    assignee: "Sarah Johnson",
    reportedAt: "2026-03-11T10:30:00Z",
    affectedSystems: "Exchange Online",
    affectedUsers: 45,
    timeline: "Detected at 10:30 AM via email filter",
    nextAction: "User training sessions scheduled",
  },
  {
    id: 2,
    title: "Suspicious VPN Activity - Off Hours",
    type: "Network",
    severity: "Critical",
    status: "Investigating",
    assignee: "Michael Chen",
    reportedAt: "2026-03-10T22:15:00Z",
    affectedSystems: "VPN Gateway",
    affectedUsers: 1,
    timeline: "Detected by SIEM at 22:15 UTC",
    nextAction: "Coordinate with law enforcement",
  },
  {
    id: 3,
    title: "Device Compliance Violations - Patch Monday",
    type: "Device Management",
    severity: "Medium",
    status: "Contained",
    assignee: "IT Admin",
    reportedAt: "2026-03-09T08:00:00Z",
    affectedSystems: "Lab Computers (12 devices)",
    affectedUsers: 0,
    timeline: "Automated scan identified overdue patches",
    nextAction: "Complete patching by 2026-03-15",
  },
  {
    id: 4,
    title: "Unauthorized File Download - Data Exfil Attempt",
    type: "DLP",
    severity: "Critical",
    status: "Remediating",
    assignee: "Lisa Wong",
    reportedAt: "2026-03-08T14:45:00Z",
    affectedSystems: "Student Records Database",
    affectedUsers: 1,
    timeline: "DLP alert triggered at 14:45. User quarantined.",
    nextAction: "Forensic analysis in progress",
  },
  {
    id: 5,
    title: "Certificate Expiration - Auth Service",
    type: "Infrastructure",
    severity: "High",
    status: "Contained",
    assignee: "Infrastructure Team",
    reportedAt: "2026-03-07T06:00:00Z",
    affectedSystems: "Authentication Service",
    affectedUsers: 0,
    timeline: "Alert triggered 30 days before expiry",
    nextAction: "Certificate renewal scheduled for 2026-04-06",
  },
  {
    id: 6,
    title: "Malware Detection - Email Attachment",
    type: "Malware",
    severity: "High",
    status: "Investigating",
    assignee: "James Wilson",
    reportedAt: "2026-03-06T11:20:00Z",
    affectedSystems: "Endpoint Protection",
    affectedUsers: 3,
    timeline: "Quarantined by antivirus before opening",
    nextAction: "Endpoint forensics and user interviews",
  },
]

export const ACCESS_LOGS = [
  {
    id: 1,
    timestamp: "2026-03-11T16:45:30Z",
    user: "sjohnson@district.k12.edu",
    role: "admin",
    action: "Login",
    resource: "Admin Console",
    ipAddress: "192.168.1.105",
    location: "IT Department",
    result: "Success",
    riskFlag: false,
  },
  {
    id: 2,
    timestamp: "2026-03-11T16:42:15Z",
    user: "unknown@external.com",
    role: "unknown",
    action: "Login Attempt",
    resource: "Student Portal",
    ipAddress: "203.0.113.42",
    location: "Unknown - International",
    result: "Failed",
    riskFlag: true,
  },
  {
    id: 3,
    timestamp: "2026-03-11T16:30:00Z",
    user: "mchen@district.k12.edu",
    role: "admin",
    action: "Export Data",
    resource: "Vendor Assessments",
    ipAddress: "192.168.1.108",
    location: "IT Department",
    result: "Success",
    riskFlag: false,
  },
  {
    id: 4,
    timestamp: "2026-03-11T16:15:45Z",
    user: "jsmith@district.k12.edu",
    role: "teacher",
    action: "Access Student Records",
    resource: "SIS Database",
    ipAddress: "192.168.2.45",
    location: "High School Building",
    result: "Success",
    riskFlag: false,
  },
  {
    id: 5,
    timestamp: "2026-03-11T16:05:20Z",
    user: "vpn-user-678@district.k12.edu",
    role: "admin",
    action: "VPN Connect",
    resource: "Corporate VPN",
    ipAddress: "198.51.100.5",
    location: "Off-Campus",
    result: "Success",
    riskFlag: true,
  },
  {
    id: 6,
    timestamp: "2026-03-11T15:50:00Z",
    user: "edavis@district.k12.edu",
    role: "teacher",
    action: "Access Student Records",
    resource: "SIS Database",
    ipAddress: "192.168.2.32",
    location: "High School Building",
    result: "Success",
    riskFlag: false,
  },
  {
    id: 7,
    timestamp: "2026-03-11T15:35:30Z",
    user: "unknown@phishing.com",
    role: "unknown",
    action: "Login Attempt",
    resource: "Email System",
    ipAddress: "198.51.100.99",
    location: "Unknown - International",
    result: "Blocked",
    riskFlag: true,
  },
  {
    id: 8,
    timestamp: "2026-03-11T15:20:15Z",
    user: "mgarcia@district.k12.edu",
    role: "teacher",
    action: "Download Report",
    resource: "Analytics Portal",
    ipAddress: "192.168.2.56",
    location: "Elementary School",
    result: "Success",
    riskFlag: false,
  },
  {
    id: 9,
    timestamp: "2026-03-11T15:05:00Z",
    user: "lwong@district.k12.edu",
    role: "admin",
    action: "Modify User Role",
    resource: "User Management",
    ipAddress: "192.168.1.110",
    location: "IT Department",
    result: "Success",
    riskFlag: false,
  },
  {
    id: 10,
    timestamp: "2026-03-11T14:50:45Z",
    user: "dkim@district.k12.edu",
    role: "teacher",
    action: "Print Request",
    resource: "Print Server",
    ipAddress: "192.168.2.40",
    location: "Middle School Building",
    result: "Success",
    riskFlag: false,
  },
  {
    id: 11,
    timestamp: "2026-03-11T14:35:20Z",
    user: "api-service-001",
    role: "system",
    action: "Data Sync",
    resource: "Student Database",
    ipAddress: "192.168.100.1",
    location: "Data Center",
    result: "Success",
    riskFlag: false,
  },
  {
    id: 12,
    timestamp: "2026-03-11T14:20:00Z",
    user: "suspicious-user@example.com",
    role: "unknown",
    action: "Brute Force Attempt",
    resource: "Email System",
    ipAddress: "203.0.113.78",
    location: "Unknown - International",
    result: "Blocked",
    riskFlag: true,
  },
  {
    id: 13,
    timestamp: "2026-03-11T14:05:30Z",
    user: "tbrown@district.k12.edu",
    role: "teacher",
    action: "Access Student Records",
    resource: "SIS Database",
    ipAddress: "192.168.2.44",
    location: "Elementary School",
    result: "Success",
    riskFlag: false,
  },
  {
    id: 14,
    timestamp: "2026-03-11T13:50:15Z",
    user: "jwilson@district.k12.edu",
    role: "admin",
    action: "Deploy Patch",
    resource: "Windows Update Service",
    ipAddress: "192.168.1.115",
    location: "IT Department",
    result: "Success",
    riskFlag: false,
  },
  {
    id: 15,
    timestamp: "2026-03-11T13:35:00Z",
    user: "panderson@district.k12.edu",
    role: "teacher",
    action: "Download Report",
    resource: "Analytics Portal",
    ipAddress: "192.168.2.58",
    location: "Middle School Building",
    result: "Success",
    riskFlag: false,
  },
  {
    id: 16,
    timestamp: "2026-03-11T13:20:45Z",
    user: "api-service-002",
    role: "system",
    action: "Backup Run",
    resource: "Backup Service",
    ipAddress: "192.168.100.2",
    location: "Data Center",
    result: "Success",
    riskFlag: false,
  },
  {
    id: 17,
    timestamp: "2026-03-11T13:05:30Z",
    user: "external-vendor@thirdparty.com",
    role: "vendor",
    action: "Access Vendor Portal",
    resource: "Vendor Management System",
    ipAddress: "198.51.100.25",
    location: "Off-Campus",
    result: "Success",
    riskFlag: false,
  },
  {
    id: 18,
    timestamp: "2026-03-11T12:50:15Z",
    user: "cjohnson@district.k12.edu",
    role: "staff",
    action: "IT Support Ticket",
    resource: "Help Desk System",
    ipAddress: "192.168.3.12",
    location: "IT Support",
    result: "Success",
    riskFlag: false,
  },
  {
    id: 19,
    timestamp: "2026-03-11T12:35:00Z",
    user: "unknown-device-xyz",
    role: "unknown",
    action: "Network Connection Attempt",
    resource: "WiFi Network",
    ipAddress: "192.168.254.200",
    location: "School Campus",
    result: "Blocked",
    riskFlag: true,
  },
  {
    id: 20,
    timestamp: "2026-03-11T12:20:45Z",
    user: "swhite@district.k12.edu",
    role: "staff",
    action: "Create User",
    resource: "User Management",
    ipAddress: "192.168.3.15",
    location: "HR Office",
    result: "Success",
    riskFlag: false,
  },
  {
    id: 21,
    timestamp: "2026-03-11T12:05:30Z",
    user: "dharris@district.k12.edu",
    role: "staff",
    action: "Financial Report Access",
    resource: "Finance System",
    ipAddress: "192.168.3.20",
    location: "Finance Office",
    result: "Success",
    riskFlag: false,
  },
  {
    id: 22,
    timestamp: "2026-03-11T11:50:15Z",
    user: "nthomas@district.k12.edu",
    role: "staff",
    action: "Facilities Request",
    resource: "Facilities Management",
    ipAddress: "192.168.3.25",
    location: "Facilities",
    result: "Success",
    riskFlag: false,
  },
  {
    id: 23,
    timestamp: "2026-03-11T11:35:00Z",
    user: "rtaylor@district.k12.edu",
    role: "teacher",
    action: "Access Student Records",
    resource: "SIS Database",
    ipAddress: "192.168.2.50",
    location: "Middle School Building",
    result: "Success",
    riskFlag: false,
  },
  {
    id: 24,
    timestamp: "2026-03-11T11:20:45Z",
    user: "jlee@district.k12.edu",
    role: "teacher",
    action: "Download Report",
    resource: "Analytics Portal",
    ipAddress: "192.168.2.52",
    location: "High School Building",
    result: "Success",
    riskFlag: false,
  },
  {
    id: 25,
    timestamp: "2026-03-11T11:05:30Z",
    user: "smartinez@district.k12.edu",
    role: "teacher",
    action: "Access Student Records",
    resource: "SIS Database",
    ipAddress: "192.168.2.48",
    location: "Elementary School",
    result: "Success",
    riskFlag: false,
  },
  {
    id: 26,
    timestamp: "2026-03-11T10:50:15Z",
    user: "srobinson@district.k12.edu",
    role: "teacher",
    action: "Access Student Records",
    resource: "SIS Database",
    ipAddress: "192.168.2.46",
    location: "High School Building",
    result: "Success",
    riskFlag: false,
  },
  {
    id: 27,
    timestamp: "2026-03-11T10:35:00Z",
    user: "backup-service-001",
    role: "system",
    action: "Daily Backup",
    resource: "Backup Service",
    ipAddress: "192.168.100.3",
    location: "Data Center",
    result: "Success",
    riskFlag: false,
  },
  {
    id: 28,
    timestamp: "2026-03-11T10:20:45Z",
    user: "monitor-service-001",
    role: "system",
    action: "Health Check",
    resource: "Monitoring Service",
    ipAddress: "192.168.100.4",
    location: "Data Center",
    result: "Success",
    riskFlag: false,
  },
  {
    id: 29,
    timestamp: "2026-03-11T10:05:30Z",
    user: "parent-user-abc@example.com",
    role: "parent",
    action: "Login",
    resource: "Parent Portal",
    ipAddress: "203.0.113.110",
    location: "Home",
    result: "Success",
    riskFlag: false,
  },
  {
    id: 30,
    timestamp: "2026-03-11T09:50:15Z",
    user: "kmartin@district.k12.edu",
    role: "parent",
    action: "Login",
    resource: "Parent Portal",
    ipAddress: "192.168.1.200",
    location: "School Campus",
    result: "Success",
    riskFlag: false,
  },
]

export const ACCESS_LOG_SUMMARY = {
  totalEvents: 4821,
  successRate: 96.2,
  failedAttempts: 183,
  blockedAttempts: 12,
  riskFlagged: 6,
}

export const SECURITY_POLICIES = [
  {
    id: 1,
    name: "Multi-Factor Authentication Policy",
    category: "Authentication",
    status: "Active",
    lastUpdated: "2026-02-15",
    owner: "Sarah Johnson",
    reviewCycle: "Annually",
    nextReview: "2027-02-15",
    version: "2.1",
    applicableTo: "All Staff & Admins",
    summary:
      "Requires MFA for all admin accounts and sensitive system access. TOTP preferred, SMS/Email acceptable.",
  },
  {
    id: 2,
    name: "Data Encryption Standards",
    category: "Data Protection",
    status: "Active",
    lastUpdated: "2026-03-01",
    owner: "Michael Chen",
    reviewCycle: "Annually",
    nextReview: "2027-03-01",
    version: "3.0",
    applicableTo: "All Data Systems",
    summary: "All sensitive data in transit (TLS 1.3) and at rest (AES-256). No exceptions.",
  },
  {
    id: 3,
    name: "Incident Response Plan",
    category: "Incident Response",
    status: "Active",
    lastUpdated: "2026-01-10",
    owner: "Lisa Wong",
    reviewCycle: "Semi-Annually",
    nextReview: "2026-07-10",
    version: "4.2",
    applicableTo: "All Staff",
    summary:
      "45-minute response SLA for P1 incidents. Escalation to superintendent within 24 hours for data breaches.",
  },
  {
    id: 4,
    name: "Vendor Risk Management",
    category: "Vendor",
    status: "Active",
    lastUpdated: "2026-02-01",
    owner: "David Kim",
    reviewCycle: "Annually",
    nextReview: "2027-02-01",
    version: "2.5",
    applicableTo: "All Vendors",
    summary: "Annual security assessment. SOC 2 or equivalent required for student data access.",
  },
  {
    id: 5,
    name: "Device Security Requirements",
    category: "Device",
    status: "Active",
    lastUpdated: "2026-02-20",
    owner: "James Wilson",
    reviewCycle: "Quarterly",
    nextReview: "2026-05-20",
    version: "1.8",
    applicableTo: "All Managed Devices",
    summary: "Monthly patching required. Antivirus mandatory. Full disk encryption for laptops.",
  },
  {
    id: 6,
    name: "Network Segmentation Policy",
    category: "Network",
    status: "Active",
    lastUpdated: "2025-11-30",
    owner: "Emma Davis",
    reviewCycle: "Annually",
    nextReview: "2026-11-30",
    version: "2.0",
    applicableTo: "Network Infrastructure",
    summary: "Student & staff networks separated. Admin access restricted to hardened networks.",
  },
  {
    id: 7,
    name: "Access Control Framework",
    category: "Authentication",
    status: "Draft",
    lastUpdated: "2026-03-05",
    owner: "Sarah Johnson",
    reviewCycle: "Quarterly",
    nextReview: "2026-06-05",
    version: "1.0",
    applicableTo: "All Users",
    summary: "Least privilege principle. Role-based access controls with quarterly reviews.",
  },
  {
    id: 8,
    name: "Password Management Policy",
    category: "Authentication",
    status: "Active",
    lastUpdated: "2025-12-01",
    owner: "Michael Chen",
    reviewCycle: "Annually",
    nextReview: "2026-12-01",
    version: "2.3",
    applicableTo: "All Users",
    summary: "Minimum 12 characters, no reuse of last 5 passwords. 90-day expiration for sensitive accounts.",
  },
  {
    id: 9,
    name: "Student Data Privacy Policy",
    category: "Data Protection",
    status: "Under Review",
    lastUpdated: "2026-02-10",
    owner: "Lisa Wong",
    reviewCycle: "Annually",
    nextReview: "2026-04-15",
    version: "3.1",
    applicableTo: "All Staff",
    summary: "FERPA & COPPA compliant. Data minimization required. Audit logs maintained.",
  },
  {
    id: 10,
    name: "Vulnerability Management Program",
    category: "Network",
    status: "Active",
    lastUpdated: "2026-01-20",
    owner: "David Kim",
    reviewCycle: "Quarterly",
    nextReview: "2026-04-20",
    version: "2.1",
    applicableTo: "All Systems",
    summary: "Monthly vulnerability scans. Critical patches within 7 days, high within 30.",
  },
  {
    id: 11,
    name: "Physical Security Controls",
    category: "Device",
    status: "Active",
    lastUpdated: "2025-10-15",
    owner: "James Wilson",
    reviewCycle: "Semi-Annually",
    nextReview: "2026-04-15",
    version: "1.5",
    applicableTo: "Server Rooms & Data Centers",
    summary: "Badge access, surveillance, environmental controls. Quarterly audits.",
  },
  {
    id: 12,
    name: "Acceptable Use Policy",
    category: "Data Protection",
    status: "Deprecated",
    lastUpdated: "2025-08-01",
    owner: "Emma Davis",
    reviewCycle: "Annually",
    nextReview: "2025-08-01",
    version: "1.2",
    applicableTo: "All Users",
    summary: "Replaced by Access Control Framework. Deprecated as of 2026-01-01.",
  },
]
